In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

In [2]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'i am a good devloper',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good devloper',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7968, 7738, 5913, 9026],
 [7968, 7738, 5913, 4438],
 [7968, 307, 5913, 9272],
 [4578, 6378, 5262, 7563, 2277],
 [4578, 6378, 5262, 7563, 6299],
 [8661, 7968, 3571, 5913, 5619],
 [4522, 2627, 1102, 7563]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7968 7738 5913 9026]
 [   0    0    0    0 7968 7738 5913 4438]
 [   0    0    0    0 7968  307 5913 9272]
 [   0    0    0 4578 6378 5262 7563 2277]
 [   0    0    0 4578 6378 5262 7563 6299]
 [   0    0    0 8661 7968 3571 5913 5619]
 [   0    0    0    0 4522 2627 1102 7563]]


In [9]:
embedding_dim=8

In [10]:
model=Sequential()
model.add(Embedding(voc_size,output_dim=embedding_dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\ADMIN\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.build(input_shape=(None, sent_length))

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 8)           │        80,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 80,000 (312.50 KB)

 Trainable params: 80,000 (312.50 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good devloper',
    'understand the meaning of words',
    'your videos are good'
]

voc_size = 10000

# One-hot encode
onehot_repr = [one_hot(words, voc_size) for words in sent]

# Pad
sent_length = 8
padded_docs = pad_sequences(onehot_repr, maxlen=sent_length, padding='pre')

# Embedding model
embedding_dim = 10
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=embedding_dim, input_length=sent_length))

# 🔹 Either build manually
model.build(input_shape=(None, sent_length))

# OR run one forward pass
# model(padded_docs)

# Now summary will work properly
model.summary()


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step


array([[[ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.00635204,  0.04172304,  0.0087068 , -0.0120417 ,
         -0.02530949,  0.01215297,  0.00051183,  0.04928633],
        [ 0.02753762, -0.00898029,  0.02329249, -0.0466051 ,
          0.00730376, -0.01660087,  0.04481346,  0.01248704],
        [ 0.04819528,  0.0159633 ,  0.03963324, -0.0271042 ,
         -0.01329045, -0.00566965, -0.01600152,  0.04815875],
        [-0.04009002,  0.02648929,  0.04478299, -0.01741688,
         -0.02602006, -0.03495004, -0.02905587,  0.00747546]],

       [[ 0.04

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7968, 7738, 5913, 9026], dtype=int32)

In [15]:
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 250ms/step


array([[[ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.04007288, -0.02552054,  0.0329499 , -0.01615796,
          0.04968366,  0.0392408 , -0.00181739,  0.03563786],
        [ 0.00635204,  0.04172304,  0.0087068 , -0.0120417 ,
         -0.02530949,  0.01215297,  0.00051183,  0.04928633],
        [ 0.02753762, -0.00898029,  0.02329249, -0.0466051 ,
          0.00730376, -0.01660087,  0.04481346,  0.01248704],
        [ 0.04819528,  0.0159633 ,  0.03963324, -0.0271042 ,
         -0.01329045, -0.00566965, -0.01600152,  0.04815875],
        [-0.04009002,  0.02648929,  0.04478299, -0.01741688,
         -0.02602006, -0.03495004, -0.02905587,  0.00747546]]],
      dtype=fl